### ISSUE TITLE
Treating failed optimizations

### ISSUE THREAD

**Issue by fdiehl** [fdiehl/apsis#131]
Currently, we treat every returned result of the optimization in the same way, regardless of it returning `3.14`, `NaN` or `"failed"`. As has been pointed out, this behaviour requires user intervention to fix (manually changing the evaluation result) and should therefore be changed, especially since GPy fails any optimization once any value is `NaN` or `inf`. This means that, once a single optimization has failed, apsis becomes useless (without user intervention).
There are several ways to treat this:
* Ignore the value, and let the optimization fail. The worst solution.
* Ignore the value and only use the other, successful evaluations to produce the next candidate. Better, but has the disadvantage that the GP will just return the failed position again (barring changes in optimization, random initialization or multiple workers)
* Set the result to some arbitrarily bad result. May cause problems with scale, i.e. setting it to 1e5 if the usual results are between 0 and 1 covers most information while if the usual results are between 1e6 and 1e10 it makes the result seem useful instead of to avoid.
* Set the result to some multiple of the current worst result. For example, any failed result is treated as ten times as bad as the current worst result. This will result in an artificial hill in the result landscape, meaning further optimizations will rather avoid it.
* Use a second Gaussian process to predict which candidates will fail. This would be nice, but has the disadvantage of requiring far more implementation work and roughly doubles the runtime.

Right now, the best approach is probably to implement an additional bool in the candidate (`failed`, default = False) which will be set when the result is `inf`, `NaN` or something similar. Then, the user has the choice (via optimizer parameter) to use one of
* `ignore`
* `fixed_value`
* `worst_multiplicator` (the default).

Later, we could then add the Gaussian prediction strategy.

**Comment by FrederikDiehl** [comment]
This is currently implemented in branch i_131_failed_optimizations, with the latest commit c4807213ad6bd65c1a0e15332be179a512618833
Some more tests will be necessary before merging.

**Comment by FrederikDiehl** [comment]
Will have to merge the branch. There are merge conflicts; I'll have to do so manually and check correctness.
