### ISSUE TITLE
Verbose naming of --continue_path

### ISSUE THREAD

**Issue by fdiehl** [fdiehl/apsis#140]
Right now, --continue_path suggests that it's only used to continue; in fact, it's used to set the whole parameter. Renaming it to a more verbose option (--storage_path?) will be necessary.

In that vein, also change logging functionality to find a better way to specify where to log.

**Comment by FrederikDiehl** [comment]
Logging could be changed by not specifying a logging path in logging.conf by default and, when it is not set, logging in continue_path. This still allows the user to define paths while keeping a reasonable default which keeps everything written to disk together. 
These changes also eliminate the differentiation between win and *nix file locations.
